In [1]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)

Array created:
 [[1 2 4]
 [5 8 7]]


In [2]:
b=np.zeros((3,4))
print("Array with all zeros:\n",b)


Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [4]:
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.28219064 0.88222197]
 [0.43421795 0.07669245]]


In [8]:
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [10]:
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
new_arr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",new_arr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [11]:
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nFlatten array:\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flatten array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [13]:
print("\nNo of dimensions:\n",arr.ndim)
print("\nShape of array:\n",arr.shape)
print("\nSize of array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element:\n",newtype)
print("\nConverted array type:\n",newtype.dtype)


No of dimensions:
 2

Shape of array:
 (3, 4)

Size of array:
 12

Array type:
 int64

Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted array type:
 float32


In [14]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[1:,1])
print(c)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[ 5  8 11 14]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
